CXXFLAGS=-ggdb -g -std=c++20 -Wall -Wextra -Wfatal-errors -pedantic
ladder:
	g++ $(CXXFLAGS) ladder_main.cpp ladder.cpp -o main
dijkstras:
	g++ $(CXXFLAGS) dijkstras_main.cpp dijkstras.cpp -o main
clean:
	/bin/rm main